# Generated by Django 4.0.6 on 2022-09-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='tag',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
